### ISSUE TITLE
Returned error: missing trie node 2f8085f8623e60106aa0fb711b495f6de52d59cc8b527b881fa773a478888a22

### ISSUE THREAD

**Issue by ymonye** [ava-labs/avalanchego#1932] opened 2023-08-27 12:13 UTC
Hi, it was recommended in the Discord to open up this issue.

I've been running an Avalanche-Go archive node for almost a year and started receiving the below errors when attempting to make C-chain JSONRPC calls for an AVAX balances. I'm not sure if my chaindata became corrupt over time (4.7 TB total), perhaps is there a way to revert my C-chain to <x> block to restart archive node syncing from that particular point?

`Returned error: missing trie node 2f8085f8623e60106aa0fb711b495f6de52d59cc8b527b881fa773a478888a22`

I was on the Cortina.8 release when the errors appeared, upgraded to Cortina.9 and still seeing the same issues.

I'm running my node with the below flags:

`docker run -d -it --ulimit nofile=1000000:1000000 --restart unless-stopped --stop-timeout 300 --log-opt max-size=10m --name avax-mainnet -v /avalanchego/mainnet:/root -p 127.0.0.1:9650:9650 -p 9651:9651 avaplatform/avalanchego:b820b46e /avalanchego/build/avalanchego --index-enabled=true --http-host=0.0.0.0 --http-port=9650 --staking-port=9651 --api-ipcs-enabled=true --chain-config-dir=/root/.avalanchego/configs/chains --http-allowed-origins=* --http-allowed-hosts=*`

My `./configs/chains/C/config.json` has the `debug` flag in the `eth-apis` section with `"pruning-enabled": false`, and has been successfully making archive & state balance requests since last year until recently.

**Comment by aaronbuchwald** [comment] 2023-08-28 18:58
What version of AvalancheGo / Coreth did you start to encounter this issue? Have you been running with archival mode enabled the whole time and never performed state sync?

This isn't enough information yet to know exactly what the issue that caused this is, but in the meantime you may want to fix your archival node with this flag: https://docs.avax.network/nodes/configure/chain-config-flags#populate-missing-tries-parallelism-int

This will start re-processing blocks at a historical point in time (specified by you ideally to either the most recent trie prior to corruption occurring or to the furthest back height that you still need to query your node) in order to re-populate missing tries. This was intended to re-populate missing tries in the case that archival mode was temporarily disabled as opposed to when the trie DB has been corrupted, so it will only re-process blocks if the root node is unavailable: https://github.com/ava-labs/coreth/blob/master/core/blockchain_iterator.go#L100. In the case of repairing trie DB corruption, this would need to change to re-processing every block and writing it to disk to handle the case that the trie root node is present, but some of its children were corrupted (most likely as a result of a bug).

Additionally, if re-processing encounters a missing trie node error then it may not finish successfully in which case you may need to try again at an earlier height where the full trie for that height is available.

**Comment by aaronbuchwald** [comment] 2023-08-28 19:00
Closing this issue in favor of tracking on Coreth since this appears to be a bug there as opposed to in AvalancheGo: https://github.com/ava-labs/coreth/issues/312

**Closed by aaronbuchwald** 2023-08-28 19:00 UTC
Labels: bug

**Comment by ymonye** [comment] 2023-08-29 01:43
> What version of AvalancheGo / Coreth did you start to encounter this issue? Have you been running with archival mode enabled the whole time and never performed state sync?
> 
> This isn't enough information yet to know exactly what the issue that caused this is, but in the meantime you may want to fix your archival node with this flag: https://docs.avax.network/nodes/configure/chain-config-flags#populate-missing-tries-parallelism-int
> 
> This will start re-processing blocks at a historical point in time (specified by you ideally to either the most recent trie prior to corruption occurring or to the furthest back height that you still need to query your node) in order to re-populate missing tries. This was intended to re-populate missing tries in the case that archival mode was temporarily disabled as opposed to when the trie DB has been corrupted, so it will only re-process blocks if the root node is unavailable: https://github.com/ava-labs/coreth/blob/master/core/blockchain_iterator.go#L100. In the case of repairing trie DB corruption, this would need to change to re-processing every block and writing it to disk to handle the case that the trie root node is present, but some of its children were corrupted (most likely as a result of a bug).
> 
> Additionally, if re-processing encounters a missing trie node error then it may not finish successfully in which case you may need to try again at an earlier height where the full trie for that height is available.

I have no idea regarding `state-sync`, but yes I have been running an archive node since September 2022 and indexing historical txns, states, AVAX balances, token balances. As stated before I was on the Cortina.8 release release when the errors occurred; at one point I had to reboot my server, restarted the AVAX docker image (built from Cortina.8) and saw that error when attempting to get AVAX balances for that particular block.

Thanks, I will see if I can populate missing txns from that block.
