### ISSUE TITLE
Sudden shutdown without any clear reason

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#737] opened 2021-01-28 01:00 UTC
**Describe the bug**
The node shuts down randomly without giving a clear reason:

```
...
INFO [01-21|16:54:56] <X Chain> avalanchego/snow/engine/avalanche/bootstrap/bootstrapper.go#395: executed 90000 operations
INFO [01-21|16:55:00] <X Chain> avalanchego/snow/engine/avalanche/bootstrap/bootstrapper.go#400: executed 91964 operations
INFO [01-21|16:55:00] <X Chain> avalanchego/snow/engine/avalanche/transitive.go#98: bootstrapping finished with 1 vertices in the accepted frontier
FATAL[01-22|00:45:06] <X Chain> avalanchego/snow/networking/router/handler.go#273: forcing chain to shutdown due to: closed to avoid possible corruption
INFO [01-22|00:45:06] <X Chain> avalanchego/snow/engine/avalanche/transitive.go#132: shutting down consensus engine
```

**To Reproduce**
Start the node and wait for a while.

**Expected behavior**
Node shouldn't shut down by itself.

**Operating System**
Linux x86_64 3.10.105 - Filesystem is btrfs

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment] 2021-01-28 01:24
Thanks for reporting this @ssg , this is caused by a database error. Currently if the node detects an abnormal database error on any operation, then it will report it as a fatal error to avoid possible database corruption that could be caused by only being able to execute some database writes, but not all of them.

Has this issue occurred multiple times? Do you have any more information about your system or what else might have been happening on your computer at the time, which might have caused a database error?

**Comment by danlaine** [comment] 2021-01-28 01:25
Hmm...it seems that leveldb errored while your node was running. What are the file descriptor limits on your machine?
I'm gonna make a PR to improve the log message

**Comment by ssg** [comment] 2021-01-28 01:39
@danlaine This is the first time this type of crash happened. I had filed another crash before.

`/proc/sys/fs/file-max` is 799198

**Comment by ssg** [comment] 2021-01-28 02:33
Logs also showed that evm plugin couldn't be found due to release package folder structure not matching avalanchego's lookup, for which I filed an issue before. Could it be that the node shut down because it couldn't integrate C-chain? It doesn't say anything other than repetitive "couldn't find plugin evm" though.

**Comment by danlaine** [comment] 2021-02-08 18:34
Closing in favor of https://github.com/ava-labs/avalanchego/issues/727 because they're very similar

**Closed by danlaine** 2021-02-08 18:34 UTC
Labels: bug
