### ISSUE TITLE
Node 1.7.3 Crash Windows versions

### ISSUE THREAD

**Issue by trancetr** [ava-labs/avalanchego#978] opened 2021-12-21 12:09 UTC
hi 
Os : Windows server 2019dc
Bugs : DB Crash
Pic : [https://i.hizliresim.com/3g5cis3.jpg](url)
1.7.3 same problem..

https://i.hizliresim.com/3g5cis3.jpg
By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by ceyonur** [comment] 2021-12-21 12:32
possible solution
> If you are experiencing the above error, you need to bootstrap from an empty database while running >= v1.7.2 for your node to become healthy.

https://github.com/ava-labs/avalanchego/issues/963#issuecomment-998234070

**Comment by StephenButtolph** [comment] 2021-12-21 15:21
Closing as a duplicate of #963

**Closed by StephenButtolph** 2021-12-21 15:21 UTC
Labels: bug
