### ISSUE TITLE
couldn't get next staker change time

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1403] opened 2023-04-22 14:40 UTC
I have run 5 nodes, all of which are normal, but this problem started to occur after startTime+initialStackDuration. It was not a problem before, was it my setting that was incorrect[
](https://github.com/ava-labs/avalanchego/issues/1366)

**Comment by StephenButtolph** [comment] 2023-04-22 20:05
Duplicate of: #1386. The primary network must never run out of all of its validators. If a network gets into a situation where there are no primary network validators - the network is not recoverable.

**Closed by StephenButtolph** 2023-04-22 20:05 UTC

**Comment by BigOceanGG** [comment] 2023-04-23 00:59
@StephenButtolph Do you mean there is no validator after startTime+initialStackDuration? What should we do at this point? Thank you

**Comment by danlaine** [comment] 2023-04-24 13:23
@BigOceanGG You have to add more primary network validators before all of the existing ones leave the validator set to ensure there are always validators
