### ISSUE TITLE
V1.7.1 failed to execute job 2MfhuQf51FbfHoHRofXp3rKUhiMG3iyCG6iUzyRdXvd2QZXAto due to failed to verify block in bootstrapping: proposed timestamp (2021-12-06 20:15:35 +0000 UTC) later than next staker change time (2021-12-06 18:37:01 +0000 UTC)

### ISSUE THREAD

**Issue by gcc2ge** [ava-labs/avalanchego#966] opened 2021-12-07 06:56 UTC
**Describe the bug**

```
ERROR[12-07|06:46:48] <P Chain> snow/engine/snowman/bootstrap/block_job.go#86: block 2MfhuQf51FbfHoHRofXp3rKUhiMG3iyCG6iUzyRdXvd2QZXAto failed verification during bootstrapping due to proposed timestamp (2021-12-06 20:15:35 +0000 UTC) later than next staker change time (2021-12-06 18:37:01 +0000 UTC)
FATAL[12-07|06:46:48] <P Chain> snow/networking/router/handler.go#144: chain shutting down due to error "failed to execute job 2MfhuQf51FbfHoHRofXp3rKUhiMG3iyCG6iUzyRdXvd2QZXAto due to failed to verify block in bootstrapping: proposed timestamp (2021-12-06 20:15:35 +0000 UTC) later than next staker change time (2021-12-06 18:37:01 +0000 UTC)" while processing message: (Op: multi_put, NodeID: NodeID-9T7NXBFpp8LWCyc58YdKNoowDipdVKAWz, RequestID: 3, NumContainers: 2000)
```

**To Reproduce**

```sh
/home/ubuntu/avalanche-node/avalanchego --config-file=/home/ubuntu/.avalanchego/configs/node.json
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7707905/144981254-54b15f78-a881-41ad-8b57-bd6b3b3697a9.png)

**Operating System**
Which OS you used to reveal the bug.
```
uname -a
Linux ip-172-31-22-204 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by p4fg** [comment] 2021-12-15 09:56
Any news? I have the same problem (different block/NodeId)

**Comment by danlaine** [comment] 2021-12-20 20:14
Closing as a duplicate of https://github.com/ava-labs/avalanchego/issues/963

**Closed by danlaine** 2021-12-20 20:14 UTC
Labels: bug
