### ISSUE TITLE
P-Chain API getSubnets unavailable for both Fuji and Mainnet

### ISSUE THREAD

**Issue by vdamle** [ava-labs/avalanchego#1221] opened 2023-02-15 05:39 UTC
**Describe the bug**
`getSubnets` P-Chain [API](https://docs.avax.network/apis/avalanchego/apis/p-chain#platformgetsubnets) is unavailable. This causes operations such as `addValidator` to fail.

**To Reproduce**
Invoke the `"platform.getSubnets"` API or run `avalanche subnet addValidator <subnet>` command

**Expected behavior**
Should fetch and display subnet information, instead returns error.

**Screenshots**

```
ubuntu@ip-<xxx>:~/avalanche-node$ avalanche subnet addValidator -k testKey --fuji  --nodeID NodeID-7smHERiKttWGYmBwxnpGJ8QBHA92eNtvC  test
Error: subnet query error: failed to decode client response: the method platform.getSubnets is not available


ubuntu@ip-172-31-32-227:~$ curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getSubnets",
    "params": {"ids":["n6qkcSMVA4SqefiVx9kcJ1cTDZFHWq9DrMdQ8Xf9XMLn6Ywe4"]},
"id": 1
}' -H 'content-type:application/json;' https://api.avax-test.network/ext/bc/P | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   255  100   108  100   147   1196   1629 --:--:-- --:--:-- --:--:--  2833
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32601,
    "message": "the method platform.getSubnets is not available"
  }
}
ubuntu@ip-172-31-32-227:~$
ubuntu@ip-172-31-32-227:~$ curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getSubnets",
    "params": {"ids":["n6qkcSMVA4SqefiVx9kcJ1cTDZFHWq9DrMdQ8Xf9XMLn6Ywe4"]},
"id": 1
}' -H 'content-type:application/json;' https://api.avax.network/ext/bc/P | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   255  100   108  100   147   1084   1476 --:--:-- --:--:-- --:--:--  2575
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32601,
    "message": "the method platform.getSubnets is not available"
  }
}
```

**Logs**
N/A

**Metrics**
N/A

**Operating System**
Linux

**Additional context**
Other P-chain APIs appear to work fine:

```
ubuntu@ip-172-31-32-227:~$ curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getPendingValidators",
    "params": {},
    "id": 1
}' -H 'content-type:application/json;' https://api.avax.network/ext/bc/P | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   380  100   278  100   102   1974    724 --:--:-- --:--:-- --:--:--  2714
{
  "jsonrpc": "2.0",
  "result": {
    "validators": [],
    "delegators": [
      {
        "txID": "DzMhirfd1DEkwm83UkApPydVE413ZqWjhDzntcGon8iyZFQTZ",
        "startTime": "1676439564",
        "endTime": "1677649164",
        "weight": "38818898136",
        "nodeID": "NodeID-Lai2VTTYk897ae9uq6cGk9FbhKD1KHvFS",
        "stakeAmount": "38818898136"
      }
    ]
  },
  "id": 1
}
```

**Comment by StephenButtolph** [comment] 2023-02-15 17:20
Avalanchego still exposes `platform.getSubnets` and `platform.getBlockchains`, so I'm going to close this issue (please feel free to re-open it on https://github.com/ava-labs/avalanche-docs, as this should be clarified in the [limitations](https://docs.avax.network/apis/avalanchego/public-api-server#limitations) section.

That being said, the public API doesn't expose all of the methods that avalanchego provides. For example, all of the `keystore` related APIs are disabled. Both `platform.getSubnets` and `platform.getBlockchains` were removed from `api.avax.network` and `api.avax-test.network` because they expose an arbitrarily large query (similarly to `platform.getValidatorsAt`, which has been disabled on the public APIs since it was introduced).

These methods are still exposed by avalanchego, and may come back in the public APIs (with some slight modifications)... But the number of requests on these endpoints was extremely low, which is why we felt comfortable removing them... Sorry for the inconvenience.

**Closed by StephenButtolph** 2023-02-15 17:20 UTC
Labels: bug

**Comment by Codie-Petersen** [comment] 2023-02-16 19:30
> Avalanchego still exposes `platform.getSubnets` and `platform.getBlockchains`, so I'm going to close this issue. Please feel free to re-open it on https://github.com/ava-labs/avalanche-docs, as this should be clarified in the [limitations](https://docs.avax.network/apis/avalanchego/public-api-server#limitations) section.
> 
> That being said, the public API doesn't expose all of the methods that avalanchego provides. For example, all of the `keystore` related APIs are disabled. Both `platform.getSubnets` and `platform.getBlockchains` were removed from `api.avax.network` and `api.avax-test.network` because they expose an arbitrarily large query (similarly to `platform.getValidatorsAt`, which has been disabled on the public APIs since it was introduced).
> 
> These methods are still exposed by avalanchego, and may come back in the public APIs (with some slight modifications)... But the number of requests on these endpoints was extremely low, which is why we felt comfortable removing them... Sorry for the inconvenience.

This is a bad take. You guys provide the CLI as a way to launch and manage subnet creation. Whatever your plans were for the backend were kind of doesn't matter. The problem is the CLI is broken with no alternative. This is the command that is broken and exposed to the public. I've tried this as well and it is broken all the way down to addValidator without any options.

```avalanche subnet addValidator -k testKey --fuji  --nodeID NodeID-7smHERiKttWGYmBwxnpGJ8QBHA92eNtvC  test```

I'd say either schedule it for removal or fix it. But all of your documentation points to using it and it doesn't work. I don't think I'd consider it closed. How are people supposed to use subnets or your brand spanking new AWS images if they don't support the full CLI?

Are you guys deprioritizing Subnets?

**Comment by vdamle** [comment] 2023-02-16 22:42
@Codie-Petersen a fix was merged for the CLI: https://github.com/ava-labs/avalanche-cli/pull/613

I tried building the CLI from this branch earlier today and can confirm that `addValidator` works with the above fix.

**Comment by Codie-Petersen** [comment] 2023-02-17 01:20
@vdamle Right on. Thanks for the heads up. Hopefully that gets integrated pretty quickly. But I'll try building from scratch. Haven't built the CLI from scratch before, but hopefully doesn't take too much effort to do for the AWS image.

Thanks again.
