### ISSUE TITLE
C Chain - Not receiving pending transactions after subscribing

### ISSUE THREAD

**Issue by mdemri** [ava-labs/avalanchego#797] opened 2021-03-06 15:59 UTC
**Describe the bug**
When I'm connecting to C chain (my own node) and subscribe to new Pending Transactions,
I'm not receiving most of the transactions

**To Reproduce**
JS client, connect to Web3 via WS, subscribe to newPendingTransactions

**Expected behavior**
Receive every new txHash in the network

**Screenshots**
None

**Operating System**
Ubuntu 20.04

**Additional context**
Node Avalanche Go version is 1.2.1 (latest)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment] 2021-03-25 19:46
Hi @mdemri are you still having this issue?
Is your node already bootstrapped?

**Comment by dmckinno** [comment] 2021-04-16 17:29
@mdemri, I don't believe that avalanchego supports this subscription. @danlaine, can you confirm?

**Comment by mdemri** [comment] 2021-04-19 06:31
I really don't understand this situation, someone has to get access to the pending tx? I was not able to enable Web3 txpool api in Avalanche node (1.3.2)

**Comment by danlaine** [comment] 2021-07-12 22:05
@mdemri Apologies for the long delay in responding. Are you still having this issue?

**Comment by danlaine** [comment] 2021-07-22 13:17
Going to close this since it's pretty old. Please re-open if you're still having this issue.

**Closed by danlaine** 2021-07-22 13:17 UTC
Labels: bug

**Comment by gebrits** [comment] 2021-09-03 15:09
Confirming this is an issue.

When subscribing to pendingTransactions, e.g: `web.eth.subscribe('pendingTransactions', ...)`, I'm only receiving transactions **once confirmed**, instead of **when pending**.  This is unexpected. 

This subscription should emit a transaction-hash once a transaction-hash enters the mempool and *not* once the hash is confirmed.
