### ISSUE TITLE
debug_traceBlockByHash returns "method handler crashed" for certain blocks

### ISSUE THREAD

**Issue by tibineacsu95** [ava-labs/avalanchego#1689] opened 2023-07-05 11:09 UTC
Hello,

We have been running multiple Avalanche Archive nodes (both mainnet and testnet) for quite some time but lately we've had some issues showing up.

For Mainnet:

Example RPC Call:

`curl http://127.0.0.1:9650/ext/bc/C/rpc -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceBlockByHash","params":["0xef836031411b2c15ef330ce28911aaf6de1995ccbdf45419fbfd4c43aa992a3e", {"tracer": "callTracer", "tracerConfig": {"onlyTopCall":false,"withLog":true}}],"id":1,"jsonrpc":"2.0"}'`

Returns:

`{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"method handler crashed"}}`

For Testnet:

Example RPC Call:

`curl https://127.0.0.1:9650/ext/bc/C/rpc -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceBlockByHash","params":["0x260238a8b034c48d2b48f40c3a34587077aefc012a96abd026e116c594c0a688", {"tracer": "prestateTracer", "tracerConfig": {"onlyTopCall": false, "diffMode": true}}],"id":1,"jsonrpc":"2.0"}'`

Returns:

`{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"method handler crashed"}}`

To give some context about the node setup environment, we are running the following binary version: `avalanche/1.10.3 [database=v1.4.5, rpcchainvm=26, commit=eb6e7973a900dc647d29a2da8e7a233ac0a5fe77]` and we have synced the nodes from scratch, given the fact that there were no official snapshots available at that time.

We were wondering whether anyone else has seen this problem before or not. Any ideas would be highly appreciated. Thanks in advance!

**Comment by StephenButtolph** [comment] 2023-07-05 13:53
This seems to share the same root cause as: #1647. The fix for this should be staged for `v1.10.4`

**Comment by tibineacsu95** [comment] 2023-07-05 14:22
Hey @StephenButtolph. Thank you for the quick response. Do you have an estimate on when the next version is scheduled to be released? After taking a quick look on #1647, I guess rolling back to v1.10.2 is also an option, but if v1.10.4 is coming in the next days, I guess it would be safer to just wait for it?

**Comment by tibineacsu95** [comment] 2023-07-05 14:34
Thanks a lot for the details, Stephen! Have a great day!

**Comment by StephenButtolph** [comment] 2023-07-06 20:46
Seems like it might slip another day (don't want you to be waiting for a fix tonight if it slips haha)

**Comment by tibineacsu95** [comment] 2023-07-06 20:47
Sure thing. Thank you for the update! Really appreciate it!

**Comment by aaronbuchwald** [comment] 2023-07-12 21:25
Thanks for re-opening and sorry we mistakenly thought this was the same issue.

Looked into this with @morrisettjohn and we have a unit test reproducing the behavior now. Going to work on cleaning it up and putting together the fix. Thanks for your patience!

**Comment by tibineacsu95** [comment] 2023-07-12 21:27
No worries at all! Glad you guys managed to reproduce it and are working on a fix. Really appreciate the update!

**Comment by aaronbuchwald** [comment] 2023-07-12 21:31
Closing in favor of https://github.com/ava-labs/coreth/issues/282 because this is an issue within Coreth.

If it's easier to follow it here, just re-open the issue with a message and I'll post an update here as well.

Thanks for reporting the issue!

**Closed by aaronbuchwald** 2023-07-12 21:31 UTC
Labels: bug
