### ISSUE TITLE
Please upgrade `golang.org/x/exp` 🙏 

### ISSUE THREAD

**Issue by ntauth** [ava-labs/avalanchego#2595] opened 2024-01-09 11:05 UTC
**Context and scope**
The package has been upgraded in `coreth` but not yet in `avalanchego`. For projects depending on `avalanchego`, this causes conflicts with other packages that rely on different versions of the package because of the differing `slices.Sort` signature

**Comment by ricardogolez** [comment] 2024-01-09 13:03
we got the same issue!

**Comment by dhrubabasu** [comment] 2024-01-10 18:50
Duplicate of #2592

**Closed by dhrubabasu** 2024-01-10 18:50 UTC
Labels: enhancement
