### ISSUE TITLE
Problem: Cyclic dependencies

### ISSUE THREAD

**Issue by ivansukach** [ava-labs/avalanchego#1223] opened 2023-02-16 23:37 UTC
**Describe the bug**
you have cyclic dependencies between **avalanchego** and **avalanche-network-runner**, **avalanchego** and **coreth**

**To Reproduce**
Go mod tidy in verbose mode or go mod graph on any repo that uses avalanche

**Expected behavior**
It is very bad practice to create cyclic dependencies. This cause errors and superfluous dependencies

**Logs**
go: github.com/ava-labs/avalanchego@v1.9.8 requires             
        github.com/ava-labs/coreth@v0.11.7-rc.0 requires        
        github.com/ava-labs/avalanchego@v1.9.8-rc.9 requires    
        github.com/ava-labs/coreth@v0.11.6-rc.0 requires        
        github.com/ava-labs/avalanche-ledger-go@v0.0.13 requires
        github.com/ava-labs/avalanchego@v1.9.2 requires
        github.com/ava-labs/avalanche-ledger-go@v0.0.11 requires
        github.com/ava-labs/avalanchego@v1.7.18 requires
        github.com/ava-labs/coreth@v0.8.16-rc.2 requires
        github.com/ava-labs/avalanchego@v1.7.17 requires
        github.com/ava-labs/coreth@v0.8.15-rc.1 requires
        github.com/ava-labs/avalanchego@v1.7.16 requires
        github.com/ava-labs/avalanche-network-runner@v1.0.6 requires
        github.com/ava-labs/avalanchego-operator@v0.0.0-20211115144351-99f07d2570bf: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs
/tags/*:refs/tags/* in C:\Users\Ivan\go\pkg\mod\cache\vcs\0d4bed232e5a07a14f862c3021d2ff8945d42678ff73dd641e3d6ea0cc529f27: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/ava-labs/avalanchego-operator/' not found

**Operating System**
Windows 10/Windows 11/ Ubuntu 18.04

**Comment by abebeos** [comment] 2023-02-17 09:48
Does this break any build? If so, could you provide a reproduction? Ideally cli.

**Comment by StephenButtolph** [comment] 2023-02-21 20:59
What version of `golang` are you using? I've attached the [results](https://github.com/ava-labs/avalanchego/files/10797677/dependencies.txt) of running `go mod graph` with `go version go1.18.5 linux/amd64`.

The references include the current repository and `avalanchego@v1.9.9-rc.3`. I certainly understand that the structure of these repositories isn't ideal... But I'm not able to replicate an actual bug.

**Comment by StephenButtolph** [comment] 2023-02-23 16:29
This feels like a duplicate of #1206 - so I'm going to close this and keep the convo there.

**Closed by StephenButtolph** 2023-02-23 16:29 UTC
Labels: question
