### ISSUE TITLE
High CPU usage on 1.0.1

### ISSUE THREAD

**Issue by jpop32** [ava-labs/avalanchego#470] opened 2020-09-30 21:45 UTC
**Describe the bug**
Since upgrading to 1.0.1 CPU usage jumped significantly.

**To Reproduce**
Start the node. After bootstrap, high usage persists. I haven't noticed correlation with queries, network activity or memory usage.

**Expected behavior**
Before 1.0.1, CPU usage was 30-40% of single core.

**Screenshots**
<img width="598" alt="Screenshot 2020-09-30 231950" src="https://user-images.githubusercontent.com/6398640/94740805-80aee500-0373-11eb-8c52-7c8359924708.png">
1.0.1 was installed on 9/29 8AM. HIgh usage persists, even after restart.

**Operating System**
Ubuntu Server 20.04, on arm64, RaspBerryPi4. Node built from source, connected to main net, and staking with 0.0121347% network share. Node is well connected (600+ peers), healthy, and running with correctly forwarded --public-ip parameter.

**Additional context**
Attached file with mem and cpu profile, as well as client output with the last 1.0.0 run that was ok and subsequent 1.0.1 runs.
[profiles.zip](https://github.com/ava-labs/avalanchego/files/5308340/profiles.zip)
There were a number of startups that failed with "Failed to connect to bootstrap nodes" errors.

<img width="1202" alt="Screenshot 2020-09-30 233523" src="https://user-images.githubusercontent.com/6398640/94742709-70e4d000-0376-11eb-9af5-5ac61a1792d9.png">

I can provide other Grafana panels if needed.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment] 2020-09-30 21:57
What about your peer counts during this time?

**Comment by jpop32** [comment] 2020-09-30 22:18
Peer count is above 600 the whole time.
<img width="601" alt="Screenshot 2020-10-01 001757" src="https://user-images.githubusercontent.com/6398640/94745756-988a6700-037b-11eb-9773-304c15e59bbb.png">

**Comment by danlaine** [comment] 2020-09-30 22:22
@jpop32 Hmm I'm still not sure...Do you think you could switch to the new metrics dashboards in here (https://github.com/ava-labs/node-monitoring) and share those? They're a little more descriptive

**Comment by jpop32** [comment] 2020-09-30 22:38
This is the general dashboard:
<img width="1201" alt="Screenshot 2020-10-01 003522" src="https://user-images.githubusercontent.com/6398640/94746932-210a0700-037e-11eb-9dea-9b343bb95001.png">
I can post the others tomorrow.

**Comment by jpop32** [comment] 2020-10-01 20:44
Good idea. Checked out revision 7120ad7336c685ab303ad25216c9ba7b2eebd4c7 (1.0.0-d). Ran it for 15 minutes:
<img width="603" alt="Screenshot 2020-10-01 211040" src="https://user-images.githubusercontent.com/6398640/94852767-a6e38c00-042a-11eb-9755-bca66a3ff61d.png">
Started ok, but rather quickly an upward slope became clear.
Went back to main net release commit: 315ac1d2fa7401f8370baedc9a4b4eaf2e9fee65. Had some 10 minutes where node was restarting, after failing to connect to bootstrap nodes. And after that, we're back to grinding the CPU:
<img width="599" alt="Screenshot 2020-10-01 214135" src="https://user-images.githubusercontent.com/6398640/94855540-f75ce880-042e-11eb-9c54-886423b72c1e.png">
So, no, this is not an issue with 1.0.1., but a different issue that just coincided with the release of v1.0.1. Correlation in this case was not causation. High CPU usage is not introduced in 1.0.1, it looks more likely to be caused by network conditions.

After switching back to HEAD commit and 1.0.1 version, I had trouble connecting to the network, and succeeded in connecting after more than 20 retries, which is interesting to note. My node is connected over wifi, but I wouldn't expect that to be a problem, wifi works fine for other devices (and speedtest shows stable 50/30Mbit over wifi). WAN is 100/100Mbit and pretty stable too, so I would rule out connectivity issues on my end. Are bootstrap nodes under excessive load?

**Comment by tasinco** [comment] 2020-10-01 20:49
The number of peers has grown, and will continue to grow.  That could absolutely have an effect on your service and on bootstrap nodes.

**Comment by danlaine** [comment] 2020-10-01 20:51
`I had trouble connecting to the network, and succeeded in connecting after more than 20 retries, which is interesting to note.`
This could be because peers you're connecting to think you're still connected from the previous run of the program...timeout disconnections take up to a minute

**Comment by danlaine** [comment] 2020-10-01 20:51
Can you look at the rest of the metrics to see if anything looks odd?

**Comment by jpop32** [comment] 2020-10-01 20:57
CPU usage doesn't look like it tracks peer counts.

Peers, last 7 days:
<img width="607" alt="Screenshot 2020-10-01 225151" src="https://user-images.githubusercontent.com/6398640/94862162-df8a6200-0438-11eb-84ce-9433d65f359b.png">

CPU, last 7 days:
<img width="602" alt="Screenshot 2020-10-01 225225" src="https://user-images.githubusercontent.com/6398640/94862244-ff218a80-0438-11eb-8b38-40ab3a26253b.png">

Things started to get progressively worse after 'too many open files' outage, three days ago. CPU was stable up until then, although there were close to 600 peers.

I'll look over the rest of the dashboards and post if anything catches my eye.

**Comment by danlaine** [comment] 2020-10-01 20:59
I'd like to know why your percentage of successful queries suddenly drops off to 0 and then suddenly comes back to ~1

Did you do a db wipe after the "too many files" crash?
Have you run with log level debug?

**Comment by danlaine** [comment] 2020-10-01 21:04
How much of your RAM is in use?

**Comment by jpop32** [comment] 2020-10-01 21:04
Well, this definitely does look odd. "Get" operations on the DB went through the roof, after the outage:

<img width="1204" alt="Screenshot 2020-10-01 230053" src="https://user-images.githubusercontent.com/6398640/94863045-1f057e00-043a-11eb-8381-52ee7ec7f016.png">

Is that the cause or the effect, I cannot tell. Does the CPU profile say anything interesting?

**Comment by jpop32** [comment] 2020-10-01 21:08
Disk activity, on the other hand, does not appear to track the increased DB activity. Graph for the last 7 days:

<img width="600" alt="Screenshot 2020-10-01 230636" src="https://user-images.githubusercontent.com/6398640/94863566-edd97d80-043a-11eb-8c79-f9720d001fd3.png">

**Comment by danlaine** [comment] 2020-10-01 21:10
What do you mean by `after the outage`? After you rebooted your node when it crashed, you mean?
The large number of database gets is super suspicious...the reason your disk activity remains low is because leveldb is caching

**Comment by danlaine** [comment] 2020-10-01 21:12
Could you run with log level debug and see if there's anything odd looking when your CPU spikes and you're doing all these database gets?

**Comment by tasinco** [comment] 2020-10-01 21:15
can you pull a new profile with the high db operations in process?

**Comment by jpop32** [comment] 2020-10-01 21:24
Yes, my node crashed with too many files open, and was down for a couple of hours. The period where successful queries drop was the day before yesterday, I'm not sure what happened there, I did restart it a couple of times because of some service config changes I did (auto-IP renewal, nothing relevant to this issue).

Memory holds steady 600-700MB for the last 7 days, even though CPU usage climbs.

I will run the node with DEBUG log level.

@tasinco The profile included in original report was from the period with high DB operations.

**Comment by jpop32** [comment] 2020-10-01 23:34
Here's a debug level log, from about half an hour of running, with high CPU load and high DB operations. You can also see a couple of unsuccessful starts in there (bootstrap nodes missing).
[gecko.zip](https://github.com/ava-labs/avalanchego/files/5315248/gecko.zip)

**Comment by tasinco** [comment] 2020-10-02 00:39
In your logging, I see a bunch of lines:
> .....engine/snowman/transitive.go#588: block failed verification due to not found, dropping block

You have tons of these in your logs.  And what the cpu.profile was indicating was a high number of sha256 activities..  And that is a bunch of cpu time because.

So I surmise that something got messed up in your DB..

**Comment by jpop32** [comment] 2020-10-02 06:00
Hm. I might have an idea what that could be. I run the node as a service. But when I shut the service down, log doesn't show the node shutting down cleanly (like with SIGINT signal when pressing ctrl-c, running from console), so I guess it just gets killed (SIGKILL) without a chance to tidy things up before exiting. And that might leave the DB in a broken state.

Another possible cause might be that sometimes while running in a 'bootstrap nodes not found' restart loop, I see `chain_router.go#99: timed out while shutting down the chains`. That might be a consequence of DB being broken, or it might leave it in a broken state because it doesn't shut down cleanly, I'm not sure.

Anyways, I'll wipe the DB and let the node re-sync from scratch, and separately investigate service startup/shutdown issue.

**Comment by jpop32** [comment] 2020-10-02 14:38
Yep, corrupted db was the culprit. Wiped it this morning and lo:

<img width="595" alt="Screenshot 2020-10-02 163511" src="https://user-images.githubusercontent.com/6398640/94935465-64bf5680-04cd-11eb-9a3f-812e80c8c81b.png">

DB ops panel also looks much healthier:

<img width="602" alt="Screenshot 2020-10-02 163634" src="https://user-images.githubusercontent.com/6398640/94935581-87516f80-04cd-11eb-984c-7f5b77112c99.png">

Remains to be seen what was the root cause of the corruption.

**Comment by CemEgri** [comment] 2020-10-02 15:37
I also had two crashes last weekend, caused by or related to high CPU usage.

The upgrade stopped the crashes, but high CPU continued. 

Reading this page, I forced a new bootstrap a few hours ago. Since, it has been a a reasonable level.

My node is on the simplest cloud server within specs.

**Comment by danlaine** [comment] 2020-10-02 15:38
@CemEgri Thanks for the data point!

**Comment by JohnJohnD** [comment] 2020-10-02 16:55
Looks like I've had the issue. I reported high CPU on Discord, including metrics screenshots (https://bit.ly/30sfpz3). I'd had the earlier crash, related to max open files. Now stopped the node, deleted the db, restarted - looking good with 4% CPU and far more reasonable db access (down from 30k operations/s, to 100-200/s). Running 1.01 on Ubuntu 20.04, 4GB, old i5 (dual core, 4 thread, 2.6GHz max, 1.3GHz base - eek)

**Comment by quasarati** [comment] 2020-10-02 18:06
Deleting the db folder helped my high CPU issue. It is now at 60% after syncing up and slowly dropping. This is similar to what I saw before during Everest and Denali, but I have to see to what level it drops eventually.

During the whole time I never saw an error in the log as far as I can recall. Maybe something needs to change to print out errors when the db is corrupted.

When I created my node I never created a user and there are no funds directly on my node.
I also made a backup of the invalid state of the db. Would it be helpful if I send that to anybody? It could be used to test validation code which triggers when this happens.

**Comment by CemEgri** [comment] 2020-10-03 11:22
Here are two culprits to look into;

1) Running with a wrong public-ip argument. (I duplicated my server with a snapshot and forgot to revise the service file. It was not just a wrong IP, it was the IP of my other working node.) This resulted in an immediate high CPU usage. 

2) Running with a screen multiplexer instead of a system service. This results in a slow increase in CPU usage.
Note: I'm not 100% sure on this one. There might have been another issue with my installation. Today I will keep it running as a service. If everything is OK, tomorrow I will try the 'screen' again. (Just for testing. I will revert to system service after the test.)

**Comment by DiCrypt1d** [comment] 2020-10-20 14:43
I have a similar problem. 2 nodes. Same pattern from time to time. CPU spikes, network is clogged and even SSH is unavailable. A restart fixes this for a random period. 1-3 days max. All software is the latest. Fresh nodes, tried everything from scratch. Screen\No screen\fresh DB etc. No luck. 1.0.3. Doubled ram to 8gb from 4gb, 6 cores EPYC 1.5gz for each. Hyper-V. Static IP.
![image](https://user-images.githubusercontent.com/51909320/96602473-b8b6a180-12fb-11eb-8d3f-4b9232d1b5fb.png)

**Comment by DiCrypt1d** [comment] 2020-10-20 14:49
My profile files generated by admin api.


[Profiles.zip](https://github.com/ava-labs/avalanchego/files/5409488/Profiles.zip)

**Comment by tasinco** [comment] 2020-10-20 14:54
@DiCrypt1d unfortunately the profiles you provided in the zip are empty..

You need to start and stop profile or the files are not generated.

**Comment by DiCrypt1d** [comment] 2020-10-20 14:58
> @DiCrypt1d unfortunately the profiles you provided in the zip are empty..
> 
> You need to start and stop profile or the files are not generated.

So I have to stop them when there is an overload occurs again? Ok. Next time will do. I thought they are kinda real-time logs.

**Comment by tasinco** [comment] 2020-10-20 15:03
Sadly the *.profile is not actually written until you stop profiling...  It just accumulates the data in memory and wont flush it...

**Comment by danlaine** [comment] 2020-10-26 13:44
Is anyone running 1.0.3 still having this issue?
If so, what CLI args are you using?

**Comment by CemEgri** [comment] 2020-10-26 14:08
Hello,

I had no problems since upgrading to 1.0.2 and deleting the database for a
fresh boostrap.

Upgrade to 1.0.3 went smoothly.

Thanks for all the efforts.

Cem Egrikavuk

**Comment by quasarati** [comment] 2020-10-26 17:34
I moved to the cloud. I still have high CPU running on a NAS, but I suspect the hardware is just underpowered and correlated to the number of connected peers. As it runs in docker I have some trouble setting up node monitoring.
Node monitoring is running in the cloud and that runs fine in a virtual. Anyway, I think my NAS issue is unrelated to this issue. If I ever get node monitoring running there I might file a new issue to see if it is really the hardware or something else is wrong.

**Comment by danlaine** [comment] 2020-10-28 19:22
Closing this. Please re-open if you have this issue again.

**Closed by danlaine** 2020-10-28 19:22 UTC
Labels: bug

**Comment by DiCrypt1d** [comment] 2020-10-31 18:58
So? I moved my nodes from Hyper-V to the latest VMware ESXi 7U1. The same problem from time to time. Also, I've flushed nodes. Installed everything from scratch again. New Ubuntu Server, New Ava 1.0.4, etc. And have filled memory and CPU profiles files now. Look below. 
[Profiles.zip](https://github.com/ava-labs/avalanchego/files/5469636/Profiles.zip)
