### ISSUE TITLE
Node killed after logs appeared

### ISSUE THREAD

**Issue by minivipers** [ava-labs/avalanchego#490] opened 2020-10-06 13:57 UTC
**Describe the bug**
while node running and bootstraping = true, unexpected logs appeared on my node and then the node stopped working

**Expected behavior**
after that, I have checked my internet connection and reset my modem. 
tried to ./avalanchego --public-ip=x.x.x.x several times... resulted with "unable to connect"
after I restart my computer, I was able to connect...and this problem has repeated 3 times in a week.

**Screenshots**

[new problem.txt](https://github.com/ava-labs/avalanchego/files/5334312/new.problem.txt)

**Operating System**
Ubuntu 18.04 lts on windows 10 pro 64 bit and avalanche version 1.0.1

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment] 2020-10-06 14:21
What version of AvalancheGo are you running?
What OS are you on?
How are you starting AvalancheGo when you get this output?

**Comment by minivipers** [comment] 2020-10-06 14:29
1) Avalanchego version 1.0.1
2) my OS is ubuntu 18.04lts running on Windows 10 pro.
3) ./avalanchego --public-ip=xx.xxx.xx.xx

**Comment by danlaine** [comment] 2020-10-06 14:34
`my OS is ubuntu 18.04lts running on Windows 10 pro.` In a virtual box? And you're sure you've configured it so that the virtual box can receive traffic on port 9651?

**Comment by minivipers** [comment] 2020-10-06 14:42
yes, I have configured both my ISP provider and Windows ports for 9651 traffic...

**Comment by danlaine** [comment] 2020-10-06 14:43
Can you reproduce the execution where these logs are printed?
Is this log file you shared the entire logs?

**Comment by minivipers** [comment] 2020-10-06 14:50
to correct your question about virtual box? No... I am using Windows Subsystem for Linux (WSL) on Windows...
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by danlaine** [comment] 2020-10-07 21:57
@mrFawkes ^ Have you seen anyone else with this issue on WSL?

**Comment by minivipers** [comment] 2020-10-08 06:02
[new problem2.txt](https://github.com/ava-labs/avalanchego/files/5345566/new.problem2.txt)
behaviour: 
1) I restart my node again.
2) graphic card started to fade to black 
3) terminal would not respond visually
4) I restart my pc
5) started my node - (problem occurs approximately 1 day period)
![IMG_20201007_193350_489](https://user-images.githubusercontent.com/15265079/95420888-f05d3b00-0944-11eb-8715-615173803f7a.jpg)
.

**Comment by danlaine** [comment] 2020-10-14 18:20
@minivipers Is this still an issue for you?

**Comment by minivipers** [comment] 2020-10-15 16:25
![image](https://user-images.githubusercontent.com/15265079/96158392-2473c580-0f1c-11eb-9ed6-b37418d50a5f.png)

**Comment by mrFawkes** [comment] 2020-10-22 13:40
@minivipers WSL is not a feature-complete solution and often causes problems due to its hybrid architecture. I would recommend you to just use either a regular Linux OS installed on your machine, a virtual box, or the experimental windows binary.

**Comment by minivipers** [comment] 2020-10-22 16:33
I have moved my node to raspberry pi 4 already and been working for a week with no problems...

**Comment by danlaine** [comment] 2020-10-22 18:18
@minivipers Ok I'm going to close this issue for now. Let us know if you have any issues going forward

**Closed by danlaine** 2020-10-22 18:18 UTC
Labels: bug

**Comment by realuser** [comment] 2021-01-14 06:19
@minivipers I wanted to try Avalanche with WSL... were you using WSL 1 or 2?

**Comment by minivipers** [comment] 2021-01-14 09:10
version 1
